aws_resource_states_file_path = "./aws-resource-state-file.toml"
region = "ap-northeast-1"

[vpc]
name = "asahi"
cidr = "172.27.0.0/16"

[[vpc_public_subnets.subnets]]
name = "asahi-public-a"
cidr = "172.27.0.0/24"
az   = "ap-northeast-1a"

[[vpc_public_subnets.subnets]]
name = "asahi-public-c"
cidr = "172.27.1.0/24"
az   = "ap-northeast-1c"

[[vpc_public_subnets.subnets]]
name = "asahi-public-d"
cidr = "172.27.2.0/24"
az   = "ap-northeast-1d"
